name: air_tickets
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ./core

  domain:
    path: ./domain


  cupertino_icons: ^1.0.6
  auto_route: ^8.1.3
  auto_route_generator: ^8.0.0
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/icons/air_tickets.png
    - assets/icons/airplane.png
    - assets/icons/alert.png
    - assets/icons/calendar.png
    - assets/icons/change.png
    - assets/icons/check.png
    - assets/icons/close.png
    - assets/icons/filter.png
    - assets/icons/fire.png
    - assets/icons/graph.png
    - assets/icons/hotel.png
    - assets/icons/left_arrow.png
    - assets/icons/mark.png
    - assets/icons/plus.png
    - assets/icons/plus_person.png
    - assets/icons/profile.png
    - assets/icons/right_arrow.png
    - assets/icons/route.png
    - assets/icons/sample.png
    - assets/icons/search.png
    - assets/icons/share.png
    - assets/icons/sphere.png
    - assets/icons/subscribe.png
    - assets/icons/tooltip.png
    - assets/images/sochi.png
    - assets/images/phuket.png
    - assets/images/istanbul.png
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png


  fonts:
    - family: SanFrancisco
      fonts:
       - asset: assets/fonts/SanFranciscoRegular.otf
         weight: 400
       - asset: assets/fonts/SanFranciscoBold.otf
         weight: 800
       - asset: assets/fonts/SanFranciscoMedium.otf
         weight: 500
       - asset: assets/fonts/SanFranciscoSemibold.otf
         weight: 600