name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  dio: ^5.4.3+1
  get_it: ^7.7.0
  pretty_dio_logger: ^1.3.1

  domain:
    path: ../domain
  data:
    path: ../data


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
